version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    tty: true
    stdin_open: true